### ISSUE TITLE
见证一个GPL3.0开源的闭源收费恰烂钱游戏辅助项目之死

### ISSUE THREAD

**Issue by KaliseD** [moxcomic/MajsoulAI#3]
**提前声明：哪怕你放源码，不公开数据集，我也能给你一点应有的尊重。**
但现在容我先来一句：好死，开香槟。
我不管你是不是亏本开发
也不管你项目的初衷是什么
你做到了假开源，你做到了卖挂恰烂钱，
你实实在在影响了游戏公平性，

*Fork下来，让历史见证一切。*
*Star一个，让大家共同参观。*
*Watch一下，看啥时候秽土转生。*

祝：
生如蜉蝣之须臾，死如你妈之无闻。
清风徐来，携先妣骨殖而上九霄。
水光潋滟，照庭中枇杷之树夭夭。

**Comment by moxcomic** [comment]
事实上我们只是和其他平台合作转型而已，至于你怎么看那不重要，因为你不了解实际原因，而这也不是真正的下线，在合作的新项目上线前我们不会公布具体情况。

**Comment by FuckUbuntu** [comment]
我的评价是骂得好。实际原因是什么不重要，事实就是破坏游戏公平性&假开源&恰烂钱，GPL开源的README.MD。

**Comment by KaliseD** [comment]
> 事实上我们只是和其他平台合作转型而已，至于你怎么看那不重要，因为你不了解实际原因，而这也不是真正的下线，在合作的新项目上线前我们不会公布具体情况。

是是是，我不了解实际情况，所以可以打着GPL开源的旗号卖挂恰钱，可以拿开源社区给自己打广告做宣传
将近百星的仓库，我以为哪个大佬开源了麻将AI，点进来一看原来是Readme
哦，合着还不是真的下线啊，那真特么遗憾。看来还真的在准备秽土转生了呢~

**Comment by EasilyGoDie** [comment]
> > 事实上我们只是和其他平台合作转型而已，至于你怎么看那不重要，因为你不了解实际原因，而这也不是真正的下线，在合作的新项目上线前我们不会公布具体情况。
> 
> 是是是，我不了解实际情况，所以可以打着GPL开源的旗号卖挂恰钱，可以拿开源社区给自己打广告做宣传 将近百星的仓库，我以为哪个大佬开源了麻将AI，点进来一看原来是Readme 哦，合着还不是真的下线啊，那真特么遗憾。看来还真的在准备秽土转生了呢~

人家开这个github就是用来打广告的。
